### PR TITLE
Implement partial songs refresh by song paths

### PR DESCRIPTION
**Pull request by FrozenAlex**
This feature should help us with much faster song refresh times when users have many songs by only loading the songs that the downloading tool passes to the function

### CODE REVIEW

**Comment by FrozenAlex** [comment]
For now I can't pass the paths through to the internal function. Span of paths seems to always turn into garbage

**Comment by FrozenAlex** [comment]
Turns out the garbage was me not ensuring the lifetime of the original vector. It seems to work well.
I'm not sure how to handle double refreshes with this function, this needs a review.

**Comment by FrozenAlex** [comment]
I need to ensure that all of my paths are loaded using this function, so double refreshes should not lose calls to this function

**Comment by FrozenAlex** [comment]
I prolly won't do anything with it. I can just do a refresh and then queue another one by waiting for events from songcore. So duplicate logic can be removed ¿ I made it based on the original function

**Comment by RedBrumbler** [comment]
this code is very broken and will likely cause the "custom levels pack" to only have the songs from the paths you refreshed, this code will not be merged as is and needs to get a rethink

unfortunately currently you're just going to have to deal with "slower" refreshes, sorry

**Comment by RedBrumbler** [comment]
also not a huge fan of just repeating the existing functions internals with minor differences, this will eventually definitely cause some issues because one place gets changed and then the change doesn't apply elsewhere.. feels very noisy

**Comment by RedBrumbler** [comment]
> this code is very broken and will likely cause the "custom levels pack" to only have the songs from the paths you refreshed, this code will not be merged as is and needs to get a rethink
> 
> unfortunately currently you're just going to have to deal with "slower" refreshes, sorry

might've misread something, doesn't look like it'd actually do that... even then I can't say I think this is a good way of adding support for this as it's a lot of code duplication rather than making the existing code work with a set of songs to reload

**Comment by FrozenAlex** [comment]
Yeah the code is not perfect. I prolly need to redo the original function but it is beyond my understanding for now.

**Comment by raineio** [comment]
Closing, and creating an issue for this

**Pull request closed without merging**
